### ISSUE TITLE
Inability to infuse

### ISSUE THREAD

**Issue by ChenZheOnePiece** [spring-cloud/spring-cloud-stream-samples#167]
I copy the following
```
	@Autowired
	@Qualifier("oddEvenSupplier-out-0")
	MessageChannel outputDestination;
```

but i can't Autowired this is my code

```

@SpringBootApplication
@RestController
public class StreamfunctionApplication {
    private static Logger logger = LoggerFactory.getLogger(StreamfunctionApplication.class);
    public static void main(String[] args) {
        SpringApplication.run(StreamfunctionApplication.class, args);
    }

    @Autowired
    @Qualifier("receive-in-0")
    private MessageChannel input;

    @Autowired
    @Qualifier("transform-out-0")
    private MessageChannel output;

    @RequestMapping(value = "/test")
    public void test(@RequestBody String msg) {
        input.send(new GenericMessage<>(msg));
    }
    @Bean
    public Function<String, String> transform() {
        return payload -> payload.toUpperCase();
    }

    //Following source is used as a test producer.
    static class TestSource {

        private AtomicBoolean semaphore = new AtomicBoolean(true);

        @Bean
        public Supplier<String> sendTestData() {
            return () -> this.semaphore.getAndSet(!this.semaphore.get()) ? "foo" : "bar";

        }
    }

    //Following sink is used as a test consumer.
    static class TestSink {

        @Bean
        public Consumer<String> receive() {
            return payload -> logger.info("Data received: " + payload);
        }
    }
}

```

```
spring:
  cloud:
    stream:
      function:
        definition: transform;sendTestData;receive
      bindings:
        transform-out-0:
          destination: xformed
        receive-in-0:
          destination: xformed
        transform-in-0:
          destination: testtock
        sendTestData-out-0:
          destination: testtock
```
