### ISSUE TITLE
ContentType configuration is not valid

### ISSUE THREAD

**Issue by ChenZheOnePiece** [spring-cloud/spring-cloud-stream-samples#169]
I config  contentType: application/json but not   available
```
spring:
  cloud:
    stream:
      default:
        contentType: application/json
      function:
        definition: sendEmail;receiveEmail;sendMsg;receiveMsg
      bindings:
        sendEmail-out-0:
          destination: email
        receiveEmail-in-0:
          destination: email
        sendMsg-out-0:
          destination: msg
        receiveMsg-in-0:
          destination: msg

```
this is my log   I want kown  when I config contentType: application/json  ,json string can automatic cast to java bean  , Or what I should do.
```
MessageProperties [headers={}, timestamp=Wed Dec 04 16:41:55 CST 2019, messageId=17b78960-e69d-e4ad-fd79-629ce8c7a013, contentType=text/plain, contentEncoding=UTF-8, contentLength=0, receivedDeliveryMode=PERSISTENT, priority=0, redelivered=false, receivedExchange=msg, receivedRoutingKey=msg, deliveryTag=1, consumerTag=amq.ctag-hhiJVa-1Y0QfVMrNIk23jg, consumerQueue=msg.anonymous.NTtI77o2RJmq3LVBr32Q0g]), contentType=text/plain, timestamp=1575448915141}]
```
