### ISSUE TITLE
How to add custom header to the DLT Event using Spring Cloud Stream

### ISSUE THREAD

**Issue by jonathanmdr** [spring-cloud/spring-cloud-stream-samples#261]
I have a consumer, and I want to set custom headers when a failure occurs in the consumer for the DLT event.

I implemented this approach, but it didn't work!

```java
@Component
public class MyConsumer implements Consumer<Message<MyEvent>> {

    @Override
    public void accept(final Message<MyEvent> event) {
        // Some logic to process the event and throws an exception
    }

    @Bean
    public DeadLetterPublishingRecoverer deadLetterPublishingRecoverer(final KafkaOperations<?, ?> kafkaOperations) {
        final DeadLetterPublishingRecoverer deadLetterPublishingRecoverer = new DeadLetterPublishingRecoverer(kafkaOperations);
        deadLetterPublishingRecoverer.setHeadersFunction((consumerRecord, exception) -> {
            final Headers headers = consumerRecord.headers();
            headers.add("foo", "bar".getBytes(StandardCharsets.UTF_8));
            return headers;
        });
        return deadLetterPublishingRecoverer;
    }

    @Bean
    public DefaultErrorHandler customDefaultErrorHandler(final DeadLetterPublishingRecoverer deadLetterPublishingRecoverer) {
        return new DefaultErrorHandler(deadLetterPublishingRecoverer);
    }

    @Bean
    public ListenerContainerCustomizer<AbstractMessageListenerContainer<byte[], byte[]>> customizer(final DefaultErrorHandler errorHandler) {
        return (container, destination, group) -> container.setCommonErrorHandler(errorHandler);
    }

}
```

How do I do this correctly?

[stackoverflow issue](https://stackoverflow.com/questions/79478209/how-to-add-custom-header-to-the-dlt-event-using-spring-cloud-stream)

**Comment by sobychacko** [comment]
Hi, I Updated the SO thread. But here is what I added as comments there.

See this related issue: https://github.com/spring-cloud/spring-cloud-stream/issues/2700
Also: https://stackoverflow.com/questions/75718833/add-custom-header-when-message-publish-to-dlq-by-spring-cloud-stream-kafka-binde
https://stackoverflow.com/questions/76133263/how-do-i-add-custom-headers-to-a-failed-message-before-it-reaches-the-dead-lette

**Comment by jonathanmdr** [comment]
Hi @sobychacko, can you help me understand what I configured wrong in my study project?

I adjusted the implementation per your link suggestions, but the custom header is not added to the event before it reaches the DLT.

```yaml
spring:
    cloud:
        function:
            definition: authorizationProcessedConsumer;authorizationProcessedDltConsumer
        stream:
            kafka:
                binder:
                    auto-create-topics: true
                bindings:
                    authorizationProcessedConsumer-in-0:
                        consumer:
                            enableDlq: true
                            dlqName: authorization-order-events-dlt
                            dlqPartitions: 1
                            autoCommitOnError: true
                            autoCommitOffset: true
                    authorizationProcessedDltConsumer-in-0:
                        consumer:
                            enableDlq: false
                            dlqName: authorization-order-events-dlt
                            dlqPartitions: 1
                            autoCommitOnError: false
                            autoCommitOffset: true
            bindings:
                authorizationProcessedConsumer-in-0:
                    destination: authorization-order-events
                    group: ${spring.application.name}
                    binder: ecommerce
                authorizationProcessedDltConsumer-in-0:
                    destination: authorization-order-events-dlt
                    group: ${spring.application.name}
                    binder: ecommerce
            binders:
                ecommerce:
                    type: kafka
                    environment:
                        spring:
                            cloud:
                                stream:
                                    kafka:
                                        binder:
                                            brokers: ${KAFKA_BROKER_HOSTS:localhost:9092}
                                            configuration:
                                                security:
                                                    protocol: ${KAFKA_PROTOCOL:SASL_PLAINTEXT}
                                                sasl:
                                                    mechanism: PLAIN
                                                    jaas:
                                                        config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"order-worker\" password=\"order-worker\";"
```

```java
@Component
public class AuthorizationProcessedConsumer implements Consumer<AuthorizationProcessedEvent> {

    private final UpdateOrderUseCase updateOrderUseCase;

    public AuthorizationProcessedConsumer(final UpdateOrderUseCase updateOrderUseCase) {
        this.updateOrderUseCase = updateOrderUseCase;
    }

    @Override
    public void accept(final AuthorizationProcessedEvent event) {
        final NotificationHandler handler = NotificationHandler.create();
        event.validate(handler);

        if (handler.hasErrors()) {
            throw DomainException.with("The authorization processed event has validation errors", handler.errors());
        }

        final UpdateOrderInput input = UpdateOrderInput.with(event.orderId(), event.status());
        this.updateOrderUseCase.execute(input);
    }

    @Bean
    public ListenerContainerWithDlqAndRetryCustomizer customizer(final KafkaOperations<?, ?> kafkaOperations) {
        return (container, destinationName, group, dlqDestinationResolver, backOff) -> {
            if (Objects.isNull(dlqDestinationResolver) || Objects.isNull(backOff)) {
                return;
            }

            final DeadLetterPublishingRecoverer deadLetterPublishingRecoverer = new DeadLetterPublishingRecoverer(kafkaOperations, dlqDestinationResolver);
            deadLetterPublishingRecoverer.setExceptionHeadersCreator((kafkaHeaders, exception, isKey, headerNames) -> {
                final String exceptionType = ExceptionUtils.getRootCauseMessage(exception);
                kafkaHeaders.add("exception-type", exceptionType.getBytes());
            });
            container.setCommonErrorHandler(new DefaultErrorHandler(deadLetterPublishingRecoverer, backOff));
        };
    }

}
```
